---

- name: Pull image from docker hub
  docker_image:
    name: binw/simple-keras-rest-api
    source: pull
    force_source: true
  register: pull_result
  retries: 10
  delay: 5
  until: pull_result is succeeded

- name: Run rest api container
  docker_container:
    name: simple-keras-rest-api
    image: binw/simple-keras-rest-api
    container_default_behavior: compatibility
    detach: true
    published_ports:
      - 80:5000
