---

- name: Get home directory
  set_fact:
    home: "{{ ansible_env.HOME }}"

# Install openjdk from the AdoptOpenJDK repository
# https://adoptopenjdk.net/installation.html#linux-pkg
- name: Make sure necessary packages are present for installing openjdk
  apt:
    name:
      - apt-transport-https
      - gnupg
      - wget
  become: true

- name: Import the AdoptOpenJDK GPG key
  apt_key:
    url: https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public
    state: present
  become: true

- name: Add AdoptOpenJDK's apt repository
  apt_repository:
    repo: deb https://adoptopenjdk.jfrog.io/adoptopenjdk/deb focal main
    state: present
  become: true

- name: Install OpenJDK 11 (with HotSpot) and maven
  apt:
    name:
      - adoptopenjdk-11-hotspot
      - maven
    update_cache: true
  become: true


- name: Clone the load generator
  git:
    repo: "https://github.com/wkk/simple-keras-rest-api"
    dest: "{{ home }}/simple-keras-rest-api"
    version: v1.1.0

- name: Download test images from GitHub
  get_url:
    url: https://github.com/umassos/edge-cloud-benchmarking/releases/download/sc21/images.zip
    dest: "{{ home }}/images.zip"
  register: download_result

- name: Install unzip
  apt:
    name: unzip
  become: true

- name: Extract images
  unarchive:
    src: "{{ home }}/images.zip"
    dest: "{{ home }}/simple-keras-rest-api/load-generator/src/test/resources"
    remote_src: true
  when: download_result.changed
