---

- set_fact:
    home: "{{ ansible_env.HOME }}"

- name: Make sure output folder exists
  file:
    path: "{{ home }}/output"
    state: directory

- name: Run health check
  uri:
    url: "http://{{ groups['master'][0] }}/check"
    method: GET
    return_content: yes
    status_code: 200
    body_format: json
  register: health_check_result

- debug:
    msg: "{{ health_check_result }}"

- name: Verify cluster health
  assert:
    that:
      - health_check_result.json.healthy

- name: Set number of requests
  set_fact:
    number_of_requests: "{{ (groups['worker'] | length) * 2000 }}"

- name: Run experiment
  shell:
    cmd: "mvn gatling:test -Dserver_address={{ groups['master'][0] }} -Dnumber_of_requests={{ number_of_requests }} -Drequest_rate={{ (groups['worker'] | length) * (item | int) }} -Dgatling.resultsFolder={{ home }}/output/{{ ts }}-{{ number_of_requests }}-{{ item }}"
    chdir: "{{ home }}/simple-keras-rest-api/load-generator"
  async: 1800
  poll: 20
  with_sequence: start=10 end=20

- name: Create archive of results
  archive:
    path: "{{ home }}/output"
    dest: "{{ home }}/output.tar.gz"

- name: Fetch results
  fetch:
    src: "{{ home }}/output.tar.gz"
    dest: "output/{{ ts }}-{{ groups['worker'] | length }}-workers/"
    flat: true

- name: Create archive of service time logs
  archive:
    path: "{{ home }}/simple-keras-rest-api/load-generator/output"
    dest: "{{ home }}/service_times.tar.gz"

- name: Fetch results
  fetch:
    src: "{{ home }}/service_times.tar.gz"
    dest: "output/{{ ts }}-{{ groups['worker'] | length }}-workers/"
    flat: true
