---

- name: Download k3s installer script
  get_url:
    url: https://get.k3s.io/
    dest: /tmp/k3s-installer.sh
    mode: 0755

- name: Install k3s
  shell: /tmp/k3s-installer.sh
  environment:
    K3S_KUBECONFIG_MODE: 644
    INSTALL_K3S_VERSION: "{{ k3s_version }}"

- name: Delete k3s installer script
  file:
    path: /tmp/k3s-installer.sh
    state: absent

- name: Read node token
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: node_token
  become: true

- name: Store Master node-token
  set_fact:
    token: "{{ node_token.content | b64decode | regex_replace('\n', '') }}"

- debug:
    msg: "token is {{ token }}"
