---

- hosts: cluster
  strategy: free
  roles:
    - role: install_docker

- hosts: cpu_worker
  strategy: free
  roles:
    - role: run_rest_api

- hosts: gpu_worker
  strategy: free
  roles:
    - role: run_rest_api_cuda

- hosts: master
  roles:
    - role: tuning
    - role: master

- hosts: load_generator
  roles:
    - role: tuning
    - role: generator
