---

- hosts: cluster
  roles:
    - role: install_docker

- hosts: worker
  strategy: free
  roles:
    - role: run_rest_api

- hosts: master
  roles:
    - role: tuning
    - role: master

- hosts: load_generator
  roles:
    - role: tuning
    - role: generator
